"""Justify: the third stage of the Candor pipeline.

Turns a Trace-verified record into one customer-facing sentence, using only
the fields Trace confirmed — never the raw case. Every generated sentence is
checked, not trusted: faithfulness (does it actually name what the record
says, with exact numbers where they matter) and plain language (no internal
jargon). Anything that fails either check, or that Trace never verified in
the first place, never reaches a customer — it comes back FAILED_REVIEW for
the review queue, same as Trace does.

The boundary line is deliberately *not* generated by the LLM: it's a fixed
line that stops a verified, faithful sentence from implying it resolved a
question it never heard (False Clarity) — a generated sentence could blur
that boundary; a fixed one can't.
"""

from packages.candor.checks import check_faithfulness, check_plain_language
from packages.candor.llm import JustifyLLMClient
from packages.candor.models import (
    DecisionRecord,
    JustificationResult,
    JustificationStatus,
    TraceOutcome,
    VerificationStatus,
)

BOUNDARY_LINE = (
    "If your concern is about this specific decision, the explanation above is complete and verified. "
    "If your concern is about the policy itself — whether it was clear, whether it's fair, whether it "
    "should exist in this form — that's a different question, and this message alone can't resolve it. "
    "We've logged it for our policy team to review."
)

APPROVED_SENTENCE = "Your request was approved. None of the rules we checked blocked it."


def justify(
    decision: DecisionRecord,
    trace_outcome: TraceOutcome,
    llm_client: JustifyLLMClient,
    justify_metadata: dict[str, dict],
) -> JustificationResult:
    if trace_outcome.verification_status != VerificationStatus.VERIFIED:
        # Never ask Justify to write a sentence for a record Trace couldn't
        # back up — that's the post-hoc-guess failure mode this pipeline
        # exists to rule out. No LLM call happens here at all.
        return JustificationResult(
            sentence="",
            boundary_line="",
            faithfulness_check_passed=False,
            plain_language_check_passed=False,
            status=JustificationStatus.FAILED_REVIEW,
        )

    failing = decision.failing_reasons
    if not failing:
        return JustificationResult(
            sentence=APPROVED_SENTENCE,
            boundary_line="",
            faithfulness_check_passed=True,
            plain_language_check_passed=True,
            status=JustificationStatus.VERIFIED,
        )

    payload = [
        {
            "description": justify_metadata.get(r.rule_id, {}).get("plain_description", r.rule_id),
            "evaluated_value": r.evaluated_value,
            "threshold": r.threshold,
            "comparator": r.comparator,
        }
        for r in failing
    ]

    sentence = llm_client.generate_sentence(payload)

    faithfulness = check_faithfulness(sentence, failing, justify_metadata)
    plain_language = check_plain_language(sentence, failing)

    if faithfulness.passed and plain_language.passed:
        return JustificationResult(
            sentence=sentence,
            boundary_line=BOUNDARY_LINE,
            faithfulness_check_passed=True,
            plain_language_check_passed=True,
            status=JustificationStatus.VERIFIED,
        )

    return JustificationResult(
        sentence=sentence,
        boundary_line="",
        faithfulness_check_passed=faithfulness.passed,
        plain_language_check_passed=plain_language.passed,
        status=JustificationStatus.FAILED_REVIEW,
    )
