"""initial schema

Revision ID: 9d5f43e22bd8
Revises: 
Create Date: 2026-09-30 11:17:23.962652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d5f43e22bd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disclosures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('CALL', 'EMAIL', 'CHAT', name='disclosure_channel'), nullable=False),
    sa.Column('disclosed_by', sa.String(length=128), nullable=False),
    sa.Column('disclosed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delay_owned', sa.Boolean(), nullable=False),
    sa.Column('sentence_sent', sa.Text(), nullable=False),
    sa.Column('customer_response', sa.Text(), nullable=True),
    sa.Column('held_up', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('justifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('boundary_line', sa.Text(), nullable=False),
    sa.Column('faithfulness_check_passed', sa.Boolean(), nullable=False),
    sa.Column('plain_language_check_passed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('VERIFIED', 'FAILED_REVIEW', name='justification_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_table('reopen_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_decision_id', sa.UUID(), nullable=False),
    sa.Column('new_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggered_decision_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['original_decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['triggered_decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('TRACE_UNRESOLVED', 'JUSTIFY_FAITHFULNESS_FAILED', 'JUSTIFY_PLAIN_LANGUAGE_FAILED', name='review_reason'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', name='review_status'), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trace_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('determinative_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'UNRESOLVED', name='verification_status'), nullable=False),
    sa.Column('counterfactual_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trace_results')
    op.drop_table('review_queue')
    op.drop_table('reopen_requests')
    op.drop_table('justifications')
    op.drop_table('disclosures')
    op.drop_table('decisions')
    op.drop_table('cases')
    # ### end Alembic commands ###
